---
version: '2.1'

services:

  auth:
    build: authenticator
    environment:
      ROUTER_URL: ws://router:8080/backend
      REALM: realm1
      SECRET_TICKET: 'super-secret'
    depends_on:
      router:
        condition: service_healthy

  node:
    build: backend
    environment:
      ROUTER_URL: ws://router:8080/backend
      REALM: realm1
      SECRET_TICKET: 'super-secret'
    depends_on:
      router:
        condition: service_healthy

  router:
    image: crossbario/crossbar
    ports:
      - 8080:8080
    environment:
      SECRET_TICKET: 'super-secret'
    volumes:
      - ./router/:/node/
    healthcheck:
      test: "test -f /node/.crossbar/node.pid"
      interval: 30s
      timeout: 10s
      retries: 5
